In [4]:
import pandas as pd
df =pd.read_csv("customer_shopping_behavior.csv")

In [5]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [7]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [9]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [13]:
df['Review Rating']= df.groupby('Category')['Review Rating'].transform(lambda x:x.fillna(x.median()))

In [15]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [20]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={"purchase_amount_(usd)":"purchase_amount"})

In [21]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [31]:
# created age group
labels = ['Young Adult','Adult','Middle-aged','Senior']
df["age_group"] = pd.qcut(df['age'],q=4,labels=labels)

In [32]:
df[['age','age_group']].head(30)

    age    age_group
0    55  Middle-aged
1    19  Young Adult
2    50  Middle-aged
3    21  Young Adult
4    45  Middle-aged
5    46  Middle-aged
6    63       Senior
7    27  Young Adult
8    26  Young Adult
9    57  Middle-aged
10   53  Middle-aged
11   30  Young Adult
12   61       Senior
13   65       Senior
14   64       Senior
15   64       Senior
16   25  Young Adult
17   53  Middle-aged
18   52  Middle-aged
19   66       Senior
20   21  Young Adult
21   31  Young Adult
22   56  Middle-aged
23   31  Young Adult
24   18  Young Adult
25   18  Young Adult
26   38        Adult
27   56  Middle-aged
28   54  Middle-aged
29   31  Young Adult

In [48]:
# created column purchase_frequency_days
frequency_mapping={
    'Fortnightly':14,
    'Weekly': 7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-weekly':14,
    'Annually':365,
    "Every 3 Months":90
}

df['purchase_frequency_days']= df['frequency_of_purchases'].map(frequency_mapping).astype('Int64')

In [49]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [51]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [54]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [55]:
df =df.drop('promo_code_used',axis=1)

In [56]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [58]:
pip install psycopg2-binary sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in C:\Users\Omkar\AppData\Roaming\Python\Python313\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in C:\Users\Omkar\AppData\Roaming\Python\Python313\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in C:\Users\Omkar\AppData\Roaming\Python\Python313\site-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Omkar\AppData\Roaming\Python\Python313\site-packages (from sqlalchemy) (4.14.1)
Note: you may need to restart the kernel to use updated packages.

In [59]:
pip install mysql-connector-python sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Collecting mysql-connector-python
  Downloading mysql_connector_python-9.6.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: sqlalchemy in C:\Users\Omkar\AppData\Roaming\Python\Python313\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in C:\Users\Omkar\AppData\Roaming\Python\Python313\site-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Omkar\AppData\Roaming\Python\Python313\site-packages (from sqlalchemy) (4.14.1)
Downloading mysql_connector_python-9.6.0-cp313-cp313-win_amd64.whl (16.5 MB)
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   --- ------------------------------------ 1.3/16.5 MB 5.5 MB/s eta 0:00:03
   ------ --------------------------------- 2.9/16.5 MB 8.2 MB/s eta 0:00:02
   -------- ------------------------------- 3.7/16.5 MB 6.4 MB/s eta 0:00:03
   ------------ --------------------------- 5.0/16.5 MB 5.8 MB/s eta 0:00:02
   ------------- -------------------------- 5.5/16.5 MB 5.6 MB/s eta 0:00:02
   ----------------- ---------------------- 7.1/16.5 MB 5.5 MB/s eta 0:00:02
   ------------------- -------------------- 8.1/16.5 MB 5.8 MB/s eta 0:00:02
   --------------------- ------------------ 8.9/16.5 MB 5.6 MB/s eta 0:00:02
   ------------------------ --------------- 10.0/16.5 MB 5.1 MB/s eta 0:00:02
   ------------------------ --------------- 10.2/16.5 MB 4.9 MB/s eta 0:00:02
   ------------------------- -------------- 10.5/16.5 MB 4.5 MB/s eta 0:00:02
   -------------------------- ------------- 11.0/16.5 MB 4.2 MB/s eta 0:00:02
   --------------------------- ------------ 11.3/16.5 MB 4.1 MB/s eta 0:00:02
   --------------------------- ------------ 11.5/16.5 MB 4.0 MB/s eta 0:00:02
   ----------------------------- ---------- 12.1/16.5 MB 3.8 MB/s eta 0:00:02
   ------------------------------ --------- 12.6/16.5 MB 3.7 MB/s eta 0:00:02
   ------------------------------- -------- 12.8/16.5 MB 3.6 MB/s eta 0:00:02
   -------------------------------- ------- 13.4/16.5 MB 3.5 MB/s eta 0:00:01
   --------------------------------- ------ 13.9/16.5 MB 3.5 MB/s eta 0:00:01
   ---------------------------------- ----- 14.2/16.5 MB 3.4 MB/s eta 0:00:01
   ----------------------------------- ---- 14.7/16.5 MB 3.3 MB/s eta 0:00:01
   ------------------------------------ --- 15.2/16.5 MB 3.3 MB/s eta 0:00:01
   -------------------------------------- - 15.7/16.5 MB 3.2 MB/s eta 0:00:01
   ---------------------------------------  16.3/16.5 MB 3.2 MB/s eta 0:00:01
   ---------------------------------------- 16.5/16.5 MB 3.1 MB/s  0:00:05
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.6.0
Note: you may need to restart the kernel to use updated packages.

In [67]:
import pandas as pd
from sqlalchemy import create_engine

# 1. Define your connection details
user = 'root'
password = 'Admin123'
host = '127.0.0.1'    # or your IP address
port = '3306'         # default MySQL port
database = 'customer_behavior'

# 2. Create the connection engine
# Format: mysql+mysqlconnector://user:password@host:port/database
engine = create_engine(f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}")

table_name="customer"
df.to_sql(table_name,engine,if_exists="replace",index=False)
print(f"data succesfully loaded into table '{table_name}' in database '{database}'.")
# # 3. Write your SQL query
# query = "SELECT * FROM your_table_name"

# # 4. Load data into a DataFrame
# df = pd.read_sql(query, con=engine)

# View the result
df.head()

data succesfully loaded into table 'customer' in database 'customer_behavior'.

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365

In [66]:
import mysql.connector

# Use this specific configuration for MySQL 9.2
config = {
    'user': 'root',
    'password': 'Admin123',
    'host': '127.0.0.1',  # 127.0.0.1 is more stable than 'localhost'
    'auth_plugin': 'caching_sha2_password'
}

try:
    conn = mysql.connector.connect(**config)
    print("✅ Success! You are connected to MySQL 9.2")
    
    # Optional: Create your database if it doesn't exist
    cursor = conn.cursor()
    cursor.execute("CREATE DATABASE IF NOT EXISTS my_jupyter_data")
    print("✅ Database 'my_jupyter_data' is ready to use.")
    
    cursor.close()
    conn.close()
    
except mysql.connector.Error as err:
    print(f"❌ Connection failed: {err}")

✅ Success! You are connected to MySQL 9.2
✅ Database 'my_jupyter_data' is ready to use.